apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: instant-ocelot-java-springboot
  janus-idp.io/tekton: instant-ocelot-java-springboot
  backstage.io/kubernetes-id: instant-ocelot-java-springboot
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: instant-ocelot-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
